spring.application.name=teste-tecnico

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.datasource.url=jdbc:mysql://db:3306/saude?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=aurora
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.connection-init-sql=SET time_zone = '+00:00';

server.port=8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
